service: to-do-serverless

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: dev
  memorySize: 128
  timeout: 10
  environment:
    IS_OFFLINE: 'false'
  stackTags:
    autoDelete: true

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - test/**
    - .gitignore
    - .git/**

custom:
  serverless-offline:
    httpPort: 3000
